version: '3.7'

services:
  gooddata-cn-ce:
    # Use the dev_latest tag which points to the latest development
    image: gooddata/gooddata-cn-ce:dev_latest
    ports:
      - "3000:3000"
      - "5432:5432"
    volumes:
      - gooddata-cn-ce-data:/data
    environment:
      LICENSE_AND_PRIVACY_POLICY_ACCEPTED: "YES"
      APP_LOGLEVEL: "INFO"
      GDCN_ENABLE_CSV_EXPORT_API: 1

  gooddata-fdw:
    build:
      context: https://github.com/gooddata/gooddata-python-sdk.git
      dockerfile: gooddata-fdw/Dockerfile
    ports:
      - "2543:5432"
    environment:
      POSTGRES_DB: gooddata
      POSTGRES_USER: gooddata
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-gooddata123}"
    command: ["postgres", "-c", "shared_preload_libraries=foreign_table_exposer", "-c", "log_statement=all", "-c", "client_min_messages=DEBUG1", "-c", "log_min_messages=DEBUG1"]

  upload-layout:
    build:
      context: https://github.com/gooddata/gooddata-python-sdk.git
      dockerfile: tests-support/Dockerfile
    environment:
      FIXTURES_DIR: /app/fixtures
      HOST: "http://gooddata-cn-ce:3000"
      HEADER_HOST: localhost
    command: ["python3", "upload_demo_layout.py"]

volumes:
  gooddata-cn-ce-data:
